on:
  push:
    tags:
      - '*'
jobs:
  export_game:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Export game
    steps:
    - name : checkout
      uses: actions/checkout@v3.3.0
    
    - name : export game
      uses: firebelley/godot-export@v5.2.0
      id: export      
      with:
        godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.2/beta5/Godot_v4.2-beta4_linux.x86_64.zip
        godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.2/beta5/Godot_v4.2-beta4_export_templates.tpz
        relative_project_path: ./
        archive_output: true
        cache: true

    - name: create release
      uses: ncipollo/release-action@v1.12.0
      with:
        token: ${{ secrets.EXPORT_GITHUB_TOKEN }}
        generateReleaseNotes: true
        tag: ${{ github.ref_name }}
        artifacts: ${{ steps.export.outputs.archive_directory }}/*